services:
  api-server:
    image: ngoctd/c72-server:latest
    restart: always
    ports:
      - "5080:5080"
    depends_on:
      - mysql

  fe:
    image: ngoctd/c72-fe:latest
    ports:
      - "5081:5081"
    depends_on:
      - api-server

volumes:
  tag:
