services:
  api-server:
    image: ngoctd/c72-server:latest
    restart: always
    environment:
      - HOST_IP=host.docker.internal
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  fe:
    image: ngoctd/c72-fe:latest
    ports:
      - "3000:3000"
    depends_on:
      - api-server

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: tag_scan
    volumes:
      - tag_scan_data:/var/lib/mysql

volumes:
  tag_scan_data:
