services:
  api-server:
    image: ngoctd/c72-server:latest
    restart: always
    ports:
      - "5080:5080"
    depends_on:
      - mysql

  fe:
    image: ngoctd/c72-fe:latest
    ports:
      - "5081:5081"
    depends_on:
      - api-server

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: laundry
    volumes:
      - tag:/var/lib/mysql
      # - C:\docker-volumes\mysql:/var/lib/mysql

volumes:
  tag:
